---
name: Weekly Typing Issue

on:
    schedule:
    # Every Monday at 09:00 UTC
        - cron: 0 9 * * 1
    workflow_dispatch:

permissions:
    contents: read
    issues: write

jobs:
    issue:
        runs-on: blacksmith-4vcpu-ubuntu-2404
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set date
              id: date
              run: echo "today=$(date -u +%F)" >> "$GITHUB_OUTPUT"

            - name: Create weekly issue
              uses: peter-evans/create-issue-from-file@v6
              with:
                  title: Weekly typing improvements – ${{ steps.date.outputs.today }}
                  content-filepath: .github/ISSUE_BODY/typing.md
                  labels: |
                      typing
                      automation
                      openhands
                  assignees: |
                      openhands
